<?php
$CONN=MYSQLI_CONNECT("localhost","root","","mydb");
IF(!$CONN)
{
ECHO "CONNECTION FAILED:".MYSQLI_CONNECT_ERROR();
}
$RESULT=MYSQLI_QUERY($CONN,"CREATE TABLE IF NOT EXISTS Student_DETAIL(O_NAME VARCHAR(30),PHN VARCHAR(10),CAR_NAME VARCHAR(30))");
IF($RESULT)
{ECHO "TABLE CREATED";}
ELSE
{ECHO "CREATION FAILED:".MYSQLI_ERROR($CONN);}
IF($_SERVER["REQUEST_METHOD"]=="POST")
{
IF(ISSET($_POST['SUBMIT']))
{
 $ONAME=$_POST['ONAME'];
 $PHN=$_POST['PHN'];
 $CARS = isset($_POST['CAR']) ? implode(", ", $_POST['CAR']) : " ";
 $TEST="INSERT INTO CAR_DETAIL VALUES('$ONAME','$PHN','$CARS')";
 $REQUEST=MYSQLI_QUERY($CONN,$TEST);
 if($REQUEST)
 {echo "record added successfully";}
}
